flaskr/routes/purchase.py
from flask import (
    Blueprint, flash, g, redirect, render_template, request, session, url_for
)
from werkzeug.exceptions import MethodNotAllowed, abort
from .auth import login_required
from flaskr.db import get_db

bp = Blueprint('purchase', __name__)

@bp.route('/list-purchases', methods=['GET'])
def list_purchases():
    user_id = g.user['id']
    db = get_db()
    user = db.execute(
        'SELECT * FROM user WHERE id = ?',
        (user_id,)
    ).fetchone()
    purchases = db.execute(
        'SELECT p.name, p.price, pur.date FROM product p'
        ' JOIN purchase AS pur ON pur.product_id = p.id'
        ' WHERE pur.user_id = ?',
        (g.user['id'],)
    ).fetchall()
    return render_template('purchase/list-purchases.html', purchases=purchases, user=user)

@bp.route('/checkout', methods=['POST', 'GET'])
def checkout():
    user_id = g.user['id']
    error = None

    if request.method == 'POST':
        cart = session['cart']
        for product in cart:
            product_id = product['id']
            payment_selected = request.form['payment']
            address_selected = request.form['address']
            db = get_db()
            db.execute(
                'INSERT INTO purchase (user_id, product_id, address, payment)'
                ' VALUES (?, ?, ?, ?)',
                (user_id, product_id, address_selected, payment_selected)
            )
            db.commit()
        session['cart'] = []
        return redirect(url_for('purchase.list_purchases'))
    return render_template('purchase/purchase.html')

@bp.route('/cart', methods=['POST', 'GET'])
@login_required
def cart():
    items = session['cart']
    if request.method == 'POST':
        return redirect(url_for('product.index'))
    return render_template('purchase/cart.html', items=items)

flaskr/templates/purchase/cart.html
{% extends 'base.html' %}

{% block header %}
  <h1>{% block title %}Your Cart {% endblock %}</h1>
{% endblock %}

{% block content %}
    <tbody>               
      {% for item in items: %}
        <td class="text-center align-middle">{{ item['id'] }}</td>
        <td class="text-center align-middle">{{ item['quantity'] }}</td>
    </tbody>
      {% endfor %}
      <td class="text-center align-middle"><a href="{{ url_for('purchase.checkout') }}">Checkout</a></td>



{% endblock %}

flaskr/templates/purchase/list-purchases.html
{% extends 'base.html' %}

{% block header %}
  <h1>{% block title %}Your Purchases, {{ user['username'] }} {% endblock %}</h1>
{% endblock %}

{% block content %}
  <table class="table">
    <thead class="thead-light">
        <tr>
            <th class="text-center">Product</th>
            <th class="text-center">Price</th>
            <th class="text-center">Purchase date</th>
            <th class="text-center"></th>
        </tr>
    </thead>
    <tbody>               
      {% for purchase in purchases: %}
        <td class="text-center align-middle">{{ purchase['name'] }}</td>
        <td class="text-center align-middle">{{ purchase['price'] }}</td>
        <td class="text-center align-middle">{{ purchase['date'] }}</td>
    </tbody>
      {% endfor %}
  </table>

{% endblock %}

flaskr/templates/purchase/purchase.html
{% extends 'base.html' %}

{% block header %}
  <h1>{% block title %} Confirm your personal information {% endblock %}</h1>
{% endblock %}

{% block content %}
  <form method="post">
    <label for="address">Address</label>
    <input name="address" id="address" required>


    <label for="payment">Choose a payment method:</label>

    <select name="payment" id="payment">
      <option value="cash">Cash</option>
      <option value="credit-debit">Credit/Debit card</option>

    </select>

    <input type="submit" value="Confirm your purchase">

</form>
{% endblock %}