flaskr/routes/product.py
from itertools import product
from flask import (
    Blueprint, flash, g, redirect, render_template, request, session, url_for
)
from werkzeug.exceptions import abort
from .auth import login_required
from flaskr.db import get_db

bp = Blueprint('product', __name__, url_prefix='/product')

@bp.route('/')
def index():
    db = get_db()
    products_list = db.execute(
        'SELECT p.id, name, description, created, user_id, username'
        ' FROM product p JOIN user u ON u.id = p.user_id'
        ' ORDER BY created DESC'
    ).fetchall()
    return render_template('product/index.html', products_list=products_list)

@bp.route('/create', methods=('GET', 'POST'))
@login_required
def create():
    if request.method == 'POST':
        name = request.form['name']
        description = request.form['description']
        price = float(request.form['price'])
        quantity = int(request.form['quantity'])
        error = None

        if not name:
            error = 'Name is required.'
        if not description:
            error = 'Description is required.'
        if not price:
            'Price is required.'
        
        if error is not None:
            flash(error)
        else:
            db = get_db()
            db.execute(
                'INSERT INTO product (name, description, price, quantity, user_id)'
                'VALUES (?, ?, ?, ?, ?)', 
                (name, description, price, quantity, g.user['id'])
            )
            db.commit()
            return redirect(url_for('product.index'))
    return render_template('product/create.html')

def get_product(id, check_author=True):
    product = get_db().execute(
        'SELECT p.id, name, description, created, user_id, username, price, quantity'
        ' FROM product p JOIN user u ON u.id = p.user_id'
        ' WHERE p.id = ?',
        (id,)
    ).fetchone()

    if product is None:
        abort(404, f"Product id {id} doesn't exist")
    
    if check_author and product['user_id'] != g.user['id']:
        abort(403)

    return product

@bp.route('/<int:id>')
def single_product(id):
    product = get_product(id, check_author=False)
    return render_template('/product/product.html', product=product)

@bp.route('/<int:id>/update', methods=('GET', 'POST'))
@login_required
def update(id):
    product = get_product(id)

    if request.method == 'POST':
        name = request.form['name']
        description = request.form['description']
        price = request.form['price']
        quantity = request.form['quantity']
        error = None

        if error is not None:
            flash(error)
        else:
            db = get_db()
            db.execute(
                'UPDATE product SET name = ?, description = ?, price = ?, quantity = ?'
                ' WHERE id = ?',
                (name, description, price, quantity, id)
            )
            db.commit()
            return redirect(url_for('product.index'))
    return render_template('product/update.html', product=product)

@bp.route('/<int:id>/delete', methods=('POST',))
@login_required
def delete(id):
    get_product(id)
    db = get_db()
    db.execute(
        'DELETE FROM product WHERE product.id = ?',
        (id,)
    )
    db.commit()
    return redirect(url_for('product.index'))

@bp.route('/<int:id>/add-to-cart', methods=['GET'])
@login_required
def add_to_cart(id):
    if not 'cart' in session:
        session['cart'] = []

    session['cart'].append({'id': id, 'quantity': 1})
    session.modified = True
    return redirect(url_for('purchase.cart'))

flaskr/templates/product/create.html
{% extends 'base.html' %}

{% block header %}
  <h1>{% block title %}New Product{% endblock %}</h1>
{% endblock %}

{% block content %}
  <form method="post">
    <label for="name">Name</label>
    <input name="name" id="name" value="{{ request.form['name'] }}" required>
    <label for="description">Description</label>
    <textarea name="description" id="description">{{ request.form['description'] }}</textarea>
    <label for="price">Price</label>
    <input name="price" id="price" type = "number" value="{{ request.form['price'] }}" required>
    <label for="quantity">Quantity</label>
    <input name="quantity" id="quantity" type = "number" value="{{ request.form['quantity'] }}" >
    <input type="submit" value="Save">
  </form>
{% endblock %}

flaskr/templates/product/index.html
{% extends 'base.html' %}

{% block header %}
  <h1>{% block title %}Products{% endblock %}</h1>
  {% if g.user %}
    <a class="action" href="{{ url_for('product.create') }}">New</a>
  {% endif %}
{% endblock %}

{% block content %}
  {% for product in products_list %}
    <article class="post">
      <header>
        <div>
          <h1>{{ product['name'] }}</h1>
          <div class="about">by {{ product['username'] }} on {{ product['created'].strftime('%Y-%m-%d') }}</div>
        </div>
          <a class="action" href="{{ url_for('product.single_product', id=product['id']) }}">View</a>
      </header>
      <p class="body">{{ product['description'] }}</p>
    </article>
    {% if not loop.last %}
      <hr>
    {% endif %}
  {% endfor %}
{% endblock %}

flaskr/templates/product/product.html
{% extends 'base.html' %}

{% block header %}
  <h1>{% block title %}{{ product['name'] }}{% endblock %}</h1>
{% endblock %}

{% block content %}
{% if g.user['id'] == product['user_id'] %}
  <form method="post">
    <label for="name">Name</label>
    <input name="name" id="name" value="{{ product['name'] }}" required>
    <label for="description">Description</label>
    <input name="description" id="description" value="{{ product['description'] }}" required>
    <label for="price">Price</label>
    <input name="price" id="price" type = "number" value="{{ product['price'] }}" required>
    <td class="text-center align-middle"><a href="{{ url_for('product.update', id = product['id']) }}">Edit</a></td>
  </form>
{% else %}
  <form>
    <label for="description">Description</label>
    <input name="description" id="description" value="{{ product['description'] }}" required>
    <label for="price">Price</label>
    <input name="price" id="price" type = "number" value="{{ product['price'] }}" required>
    <label for="quantity">Quantity</label>
    <input name="quantity" id="quantity" type= "number" value = "{{ product['quantity'] }}"required>
    <td class="text-center align-middle"><a href="{{ url_for('product.add_to_cart', id=product['id'], quantity=request.form['quantity']) }}">Add to cart</a></td>

    <form href="{{ url_for('product.add_to_cart', id=product['id'], quantity=request.form['quantity']) }}" method="post">
      <input type="submit" method = "post" value="Add to cart" onclick="return confirm('Are you sure?');">
    </form>

  </form>
{% endif %}
{% endblock %}

flaskr/templates/product/update.html
{% extends 'base.html' %}

{% block header %}
  <h1>{% block title %}Edit "{{ product['name'] }}"{% endblock %}</h1>
{% endblock %}

{% block content %}
  <form method="post">
    <label for="name">Name</label>
    <input name="name" id="name"
      value="{{ request.form['name'] or product['name'] }}" required>
    <label for="description">Description</label>
    <textarea name="description" id="description">{{ request.form['description'] or product['description'] }}</textarea>
    <label for="price">Price</label>
    <input name="price" id="price"
      value="{{ request.form['price'] or product['price'] }}" required>
    <label for="quantity">Quanitty</label>
    <input name="quantity" id="quantity"
      value="{{ request.form['quantity'] or product['quantity'] }}" required>
    <input type="submit" value="Save">
  </form>
  <hr>
  <form action="{{ url_for('product.delete', id=product['id']) }}" method="post">
    <input class="danger" type="submit" value="Delete" onclick="return confirm('Are you sure?');">
  </form>
{% endblock %}